[2024-03-22T18:46:21.557+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: milestone3.clean_data scheduled__2024-03-22T18:44:00+00:00 [queued]>
[2024-03-22T18:46:21.564+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: milestone3.clean_data scheduled__2024-03-22T18:44:00+00:00 [queued]>
[2024-03-22T18:46:21.565+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-03-22T18:46:21.565+0000] {taskinstance.py:1369} INFO - Starting attempt 2 of 2
[2024-03-22T18:46:21.565+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-03-22T18:46:21.576+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): clean_data> on 2024-03-22 18:44:00+00:00
[2024-03-22T18:46:21.587+0000] {standard_task_runner.py:52} INFO - Started process 1749 to run task
[2024-03-22T18:46:21.591+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'milestone3', 'clean_data', 'scheduled__2024-03-22T18:44:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_elia_DAG.py', '--cfg-path', '/tmp/tmptulv0jbv', '--error-file', '/tmp/tmpaol0amsj']
[2024-03-22T18:46:21.594+0000] {standard_task_runner.py:80} INFO - Job 183: Subtask clean_data
[2024-03-22T18:46:21.679+0000] {task_command.py:371} INFO - Running <TaskInstance: milestone3.clean_data scheduled__2024-03-22T18:44:00+00:00 [running]> on host b79cb602ca97
[2024-03-22T18:46:21.862+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=elia
AIRFLOW_CTX_DAG_ID=milestone3
AIRFLOW_CTX_TASK_ID=clean_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-22T18:44:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-22T18:44:00+00:00
[2024-03-22T18:46:21.866+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_elia_DAG.py", line 41, in clean
    df=pd.read_csv('/opt/airflow/dags/customer.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/customer.csv'
[2024-03-22T18:46:21.878+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=milestone3, task_id=clean_data, execution_date=20240322T184400, start_date=20240322T184621, end_date=20240322T184621
[2024-03-22T18:46:21.886+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 183 for task clean_data ([Errno 2] No such file or directory: '/opt/airflow/dags/customer.csv'; 1749)
[2024-03-22T18:46:21.899+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-22T18:46:21.933+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
