[2024-03-22T18:47:08.361+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: milestone3.clean_data scheduled__2024-03-22T18:45:00+00:00 [queued]>
[2024-03-22T18:47:08.370+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: milestone3.clean_data scheduled__2024-03-22T18:45:00+00:00 [queued]>
[2024-03-22T18:47:08.371+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-03-22T18:47:08.371+0000] {taskinstance.py:1369} INFO - Starting attempt 2 of 2
[2024-03-22T18:47:08.371+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-03-22T18:47:08.380+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): clean_data> on 2024-03-22 18:45:00+00:00
[2024-03-22T18:47:08.389+0000] {standard_task_runner.py:52} INFO - Started process 1771 to run task
[2024-03-22T18:47:08.399+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'milestone3', 'clean_data', 'scheduled__2024-03-22T18:45:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_elia_DAG.py', '--cfg-path', '/tmp/tmpmekg1pus', '--error-file', '/tmp/tmprmqbn1me']
[2024-03-22T18:47:08.408+0000] {standard_task_runner.py:80} INFO - Job 186: Subtask clean_data
[2024-03-22T18:47:08.501+0000] {task_command.py:371} INFO - Running <TaskInstance: milestone3.clean_data scheduled__2024-03-22T18:45:00+00:00 [running]> on host b79cb602ca97
[2024-03-22T18:47:08.554+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=elia
AIRFLOW_CTX_DAG_ID=milestone3
AIRFLOW_CTX_TASK_ID=clean_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-22T18:45:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-22T18:45:00+00:00
[2024-03-22T18:47:08.557+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_elia_DAG.py", line 41, in clean
    df=pd.read_csv('/opt/airflow/dags/P2M3_elia_data_raw.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/P2M3_elia_data_raw.csv'
[2024-03-22T18:47:08.566+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=milestone3, task_id=clean_data, execution_date=20240322T184500, start_date=20240322T184708, end_date=20240322T184708
[2024-03-22T18:47:08.574+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 186 for task clean_data ([Errno 2] No such file or directory: '/opt/airflow/dags/P2M3_elia_data_raw.csv'; 1771)
[2024-03-22T18:47:08.620+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-22T18:47:08.653+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
