[2024-03-22T17:24:57.340+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: milestone3.fetch_data_from_progresql scheduled__2024-03-22T17:22:00+00:00 [queued]>
[2024-03-22T17:24:57.347+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: milestone3.fetch_data_from_progresql scheduled__2024-03-22T17:22:00+00:00 [queued]>
[2024-03-22T17:24:57.347+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-03-22T17:24:57.347+0000] {taskinstance.py:1369} INFO - Starting attempt 2 of 2
[2024-03-22T17:24:57.347+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-03-22T17:24:57.368+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): fetch_data_from_progresql> on 2024-03-22 17:22:00+00:00
[2024-03-22T17:24:57.385+0000] {standard_task_runner.py:52} INFO - Started process 247 to run task
[2024-03-22T17:24:57.407+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'milestone3', 'fetch_data_from_progresql', 'scheduled__2024-03-22T17:22:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_elia_DAG.py', '--cfg-path', '/tmp/tmprlvbq8lg', '--error-file', '/tmp/tmpz8yu262f']
[2024-03-22T17:24:57.411+0000] {standard_task_runner.py:80} INFO - Job 8: Subtask fetch_data_from_progresql
[2024-03-22T17:24:57.499+0000] {task_command.py:371} INFO - Running <TaskInstance: milestone3.fetch_data_from_progresql scheduled__2024-03-22T17:22:00+00:00 [running]> on host b79cb602ca97
[2024-03-22T17:24:57.579+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=elia
AIRFLOW_CTX_DAG_ID=milestone3
AIRFLOW_CTX_TASK_ID=fetch_data_from_progresql
AIRFLOW_CTX_EXECUTION_DATE=2024-03-22T17:22:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-22T17:22:00+00:00
[2024-03-22T17:24:57.582+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_elia_DAG.py", line 25, in fetch_data
    connection = psycopg2.connect(connection_string)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "milestone" does not exist

[2024-03-22T17:24:57.591+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=milestone3, task_id=fetch_data_from_progresql, execution_date=20240322T172200, start_date=20240322T172457, end_date=20240322T172457
[2024-03-22T17:24:57.599+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task fetch_data_from_progresql (FATAL:  database "milestone" does not exist
; 247)
[2024-03-22T17:24:57.620+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-22T17:24:57.653+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
