[2024-03-22T18:18:52.821+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: milestone3.fetch_data_from_progresql manual__2024-03-22T18:18:50.832066+00:00 [queued]>
[2024-03-22T18:18:52.830+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: milestone3.fetch_data_from_progresql manual__2024-03-22T18:18:50.832066+00:00 [queued]>
[2024-03-22T18:18:52.830+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-03-22T18:18:52.830+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2024-03-22T18:18:52.830+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-03-22T18:18:52.839+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): fetch_data_from_progresql> on 2024-03-22 18:18:50.832066+00:00
[2024-03-22T18:18:52.848+0000] {standard_task_runner.py:52} INFO - Started process 1228 to run task
[2024-03-22T18:18:52.850+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'milestone3', 'fetch_data_from_progresql', 'manual__2024-03-22T18:18:50.832066+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_elia_DAG.py', '--cfg-path', '/tmp/tmp58bmx8rr', '--error-file', '/tmp/tmpezf4gi8p']
[2024-03-22T18:18:52.852+0000] {standard_task_runner.py:80} INFO - Job 119: Subtask fetch_data_from_progresql
[2024-03-22T18:18:52.909+0000] {task_command.py:371} INFO - Running <TaskInstance: milestone3.fetch_data_from_progresql manual__2024-03-22T18:18:50.832066+00:00 [running]> on host b79cb602ca97
[2024-03-22T18:18:53.026+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=elia
AIRFLOW_CTX_DAG_ID=milestone3
AIRFLOW_CTX_TASK_ID=fetch_data_from_progresql
AIRFLOW_CTX_EXECUTION_DATE=2024-03-22T18:18:50.832066+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-22T18:18:50.832066+00:00
[2024-03-22T18:18:53.028+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_elia_DAG.py", line 25, in fetch_data
    connection = psycopg2.connect(connection_string)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5434?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5434?

[2024-03-22T18:18:53.041+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=milestone3, task_id=fetch_data_from_progresql, execution_date=20240322T181850, start_date=20240322T181852, end_date=20240322T181853
[2024-03-22T18:18:53.050+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 119 for task fetch_data_from_progresql (could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5434?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5434?
; 1228)
[2024-03-22T18:18:53.073+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-22T18:18:53.105+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
