[2024-03-22T17:35:01.174+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: milestone3.fetch_data_from_progresql scheduled__2024-03-22T17:34:00+00:00 [queued]>
[2024-03-22T17:35:01.181+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: milestone3.fetch_data_from_progresql scheduled__2024-03-22T17:34:00+00:00 [queued]>
[2024-03-22T17:35:01.182+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-03-22T17:35:01.182+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2024-03-22T17:35:01.182+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-03-22T17:35:01.191+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): fetch_data_from_progresql> on 2024-03-22 17:34:00+00:00
[2024-03-22T17:35:01.196+0000] {standard_task_runner.py:52} INFO - Started process 433 to run task
[2024-03-22T17:35:01.199+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'milestone3', 'fetch_data_from_progresql', 'scheduled__2024-03-22T17:34:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_elia_DAG.py', '--cfg-path', '/tmp/tmpkw10kkbq', '--error-file', '/tmp/tmpis7v8g_s']
[2024-03-22T17:35:01.200+0000] {standard_task_runner.py:80} INFO - Job 30: Subtask fetch_data_from_progresql
[2024-03-22T17:35:01.290+0000] {task_command.py:371} INFO - Running <TaskInstance: milestone3.fetch_data_from_progresql scheduled__2024-03-22T17:34:00+00:00 [running]> on host b79cb602ca97
[2024-03-22T17:35:01.345+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=elia
AIRFLOW_CTX_DAG_ID=milestone3
AIRFLOW_CTX_TASK_ID=fetch_data_from_progresql
AIRFLOW_CTX_EXECUTION_DATE=2024-03-22T17:34:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-22T17:34:00+00:00
[2024-03-22T17:35:01.349+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_elia_DAG.py", line 25, in fetch_data
    connection = psycopg2.connect(connection_string)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "milestone" does not exist

[2024-03-22T17:35:01.358+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=milestone3, task_id=fetch_data_from_progresql, execution_date=20240322T173400, start_date=20240322T173501, end_date=20240322T173501
[2024-03-22T17:35:01.366+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 30 for task fetch_data_from_progresql (FATAL:  database "milestone" does not exist
; 433)
[2024-03-22T17:35:01.380+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-22T17:35:01.411+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
